JBoard2696/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("board/", include("board.urls")),
    path('admin/', admin.site.urls),
]

board/urls.py
from django.urls import path

from . import views

app_name = "board"
urlpatterns = [
    
    path("", views.index, name="index"), #just for testing
    path("front/", views.front, name="front"), #front page of the job board. 
    path("front/<int:pk>", views.singlejobview), #view a single job with or without logging in
    path("login/", views.login_page, name="login"), #log in a User or a Seeker
    path("logout", views.logout_request, name="logout"),
    path("register/", views.sign_up, name="register"), #register a new User
    path("password-change/", views.change_password, name="password-change"),

    path("seekerview/", views.seekerview, name="seekerview"), #seeker home page
    path("seekeredit/", views.seekeredit, name="seekeredit"), #seeker edit profile
    path("seekeroneview/<int:pk>", views.seekeroneview),
    path("jobcreate/", views.jobcreate, name="jobcreate"),
    path("jobedit/<int:pk>", views.jobedit, name="edit_job"),
    path("jobpublish/<int:pk>", views.jobpublish, name="publishjob"),
    path("jobunpublish/<int:pk>", views.jobunpublish, name="unpublishjob"),
    path("jobdelete/<int:pk>", views.jobdelete, name="deletejob"),

    path("userview/", views.userview, name="userhome"), #User home page
    path("useredit/", views.useredit, name="useredit"), #User edit profile
    path("cvcreate/", views.cvcreate, name="newcv"), #create a cv, edit a cv
    path("cvview/", views.cvview, name="seecv"), #look at User's current CV
    path("cvedit/", views.cvedit, name="editcv"),
    
    path("seeapply/<int:pk>", views.seeapply, name="seeapply"), #see application + cv
    path("jobapply/<int:pk>", views.jobapply, name="applyjob"), #apply to a job
    path("applycancel/<int:pk>", views.applycancel, name="applycancel"), #cancel application
    path("motivation/", views.jobapply, name="motivation"), #i need a html, do i need a path?
    
    path("cvexport/", views.cvexport, name="exportcv"), #HttpResponse only
]

board/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile, Curriculum, JobPosition, JobApply
from django.forms.widgets import PasswordInput

class RegisterForm(UserCreationForm): #works
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    date_of_birth = forms.DateField(required=False, help_text="YYYY-MM-DD")
    is_seeker = forms.BooleanField(required=False, help_text="Registering to seek employees? Tick this!")
    company_name = forms.CharField(required=False, max_length=200, help_text="Company Name")
    creg_number = forms.CharField(required=False, max_length=8, help_text="Company Serial Number")
   
    class Meta:
        model = User
        fields = ['username']


class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=65, required=True)
    email = forms.EmailField(required=False)
    class Meta:
        model = User
        fields = ['username', 'email']

  

class UserProfileEdit(forms.ModelForm): #edit only User fields and UserProfile jobless field
    class Meta:
        model = UserProfile
        fields = [
            "first_name",
            "last_name",
            "email",
            "date_of_birth",   
        ]

class SeekerProfileEdit(forms.ModelForm): #edit only User fields and UserProfile jobless fields
    class Meta:
        model = UserProfile
        fields = [
            "first_name",
            "last_name",
            "email",
            "date_of_birth", 
            "company_name", 
            "creg_number",
            "company_descript",
        ]     


class CurriculumForm(forms.ModelForm):
    class Meta:
        model = Curriculum
        fields = [
            "cv_education",
            "cv_career",
            "cv_skills",
            "cv_other",
        ]


class JobPositionForm(forms.ModelForm):
    class Meta:
        model = JobPosition
        fields = [
            "job_title",
            "job_desc",
            "job_field",
            "job_skills",
            "published",
        ] 

class MotivationForm(forms.ModelForm):
    class Meta:
        model = JobApply
        fields = ["motivation"]

board/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group
from django.forms.models import model_to_dict
from .models import *
from .forms import *
from . import forms
from .functions import *
#superuser - pixelad
#pw - samantha23

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")
# Create your views here.

def front(request):
    job_list = JobPosition.objects.filter(published=True).order_by("job_date") #shows only posts which are not drafts
    context = {"job_list" : job_list}
    return render(request, "board/front.html", context) 
    

def sign_up(request): 
    if request.method =="POST":
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()
            user.userprofile.first_name = user_form.cleaned_data.get("first_name")
            user.userprofile.last_name = user_form.cleaned_data.get("last_name")
            user.userprofile.email = user_form.cleaned_data.get("email")
            user.userprofile.date_of_birth = user_form.cleaned_data.get("date_of_birth")
            user.userprofile.is_seeker = user_form.cleaned_data.get("is_seeker")
            user.userprofile.company_name = user_form.cleaned_data.get("company_name")
            user.userprofile.creg_number = user_form.cleaned_data.get("creg_number")
            user.save()
            my_jobless = Group.objects.get(name="Jobless")
            my_seeker = Group.objects.get(name="Seeker")
            if user.userprofile.is_seeker == True:
                my_seeker.user_set.add(user)
            else:
                my_jobless.user_set.add(user)
            return redirect("board:front")
        
    else:
        user_form = RegisterForm()
        return render(request, 'board/registration.html', {'user_form' : user_form})      
    #OPTION 8 - CRUNCHYDATA JUNE 22, 2020 BLOG POST - WORKS

def login_page(request):
    form = forms.LoginForm()
    if request.method =="POST":
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                if user.is_active:
                    request.session.set_expiry(86400)
                    login(request, user)
                    if user.groups.filter(name="Jobless").exists():
                        return redirect('board:userhome')
                    elif user.groups.filter(name="Seeker").exists():
                        return redirect('board:seekerview')
                    else:
                        return redirect('board:front')
            else:
                message = "Did you use the right username and password?"
                return render(request, 'board/login.html', {'form': form, "message" : message})
    else:
        return render(request, 'board/login.html', {'form': form})

@login_required   
def logout_request(request):
    logout(request)
    return redirect("board:front")

@login_required
@user_passes_test(is_seeker)
def seekerview(request): #html exists
    current_user = request.user
    j = None
    seeker_job_list = JobPosition.objects.filter(job_user=current_user)
    for i in seeker_job_list:
            j = i.job_id
    applications = JobApply.objects.filter(sourcejob=j)
    context={
        "current_user" : current_user,
        "seeker_job_list" : seeker_job_list,
        "applications" : applications,
        
    }
    return render(request, "board/seekerview.html", context=context)

@login_required
@user_passes_test(is_seeker)
def jobcreate(request): #html exists
    employer = request.user
    employer_profile = employer.userprofile

    if request.method=="POST":
        form = JobPositionForm(request.POST, files=request.FILES)
        if form.is_valid():
            newjob = form.save(commit=False)
            newjob.job_user = employer
            newjob.email = employer_profile.email
            newjob.job_source = employer_profile.company_name
            newjob.job_about = employer_profile.company_descript
            newjob.save()
            return redirect("board:seekerview") 
    else:
        form = JobPositionForm()
        return render(request, 'board/jobcreate.html', {"form" : form})
    

def singlejobview(request, pk): #html exists
    try:
        job_one = JobPosition.objects.get(job_id=pk) 
    except JobPosition.DoesNotExist:
        raise Http404("The job posting does not exist")
    return render(request, "board/openingsingle.html", {"job_one" : job_one})

@login_required
@user_passes_test(is_seeker)
def seekeroneview(request, pk):
    try:
        job_one = JobPosition.objects.get(job_id=pk)
        applications = JobApply.objects.filter(sourcejob=job_one) 
    except JobPosition.DoesNotExist:
        raise Http404("The job posting does not exist")
    return render(request, "board/seekeroneview.html", {"job_one" : job_one, "applications" : applications})

@login_required
@user_passes_test(is_seeker)
def jobpublish(request, pk): 
    opening = JobPosition.objects.get(job_id=pk)
    if request.method == "POST":
        if opening.published == False:
            opening.published = True
            opening.save()
            return redirect ("board:seekerview")

@login_required
@user_passes_test(is_seeker)
def jobunpublish(request, pk): 
    opening = JobPosition.objects.get(job_id=pk)
    if request.method == "POST":
        if opening.published == True:
            opening.published = False
            opening.save()
            return redirect ("board:seekerview")

@login_required
@user_passes_test(is_seeker)
def jobdelete(request, pk): #Html exists.
    opening = JobPosition.objects.get(job_id=pk)
    if request.method == "POST":
        opening.delete()
        return redirect("board:seekerview")
    else:
        return redirect("board:seekerview")

@login_required
@user_passes_test(is_seeker)
def jobedit(request, pk): #html exists. 
    employer = request.user
    employer_profile = employer.userprofile
    job =JobPosition.objects.get(job_id=pk)
    if request.method=="POST":
        form = JobPositionForm(request.POST)
        if form.is_valid():
            edit = form.save(commit=False)
            edit.job_user = employer
            edit.job_source = employer_profile.company_name
            edit.job_id = job.job_id
            edit.save()
            return redirect("board:seekerview")
        else:
            form = JobPositionForm(initial=model_to_dict(job))
            return render(request, 'board/jobedit.html', {'form' : form})
    else:
        form = JobPositionForm(initial=model_to_dict(job))
        return render(request, 'board/jobedit.html', {'form' : form})


@login_required
@user_passes_test(is_jobless)
def userview(request): #html exists
    apply_list = None
    try:
        jobless = request.user
        message = "You have not created a CV yet"
        seevee = Curriculum.objects.get(profile=jobless)
        apply_list = JobApply.objects.filter(applicant=jobless)
    except Curriculum.DoesNotExist:
        return render(request, "board/userview.html", {"jobless" : jobless, "message" : message, "apply_list" : apply_list})
    return render(request, "board/userview.html", {"jobless" : jobless, "seevee" : seevee, "apply_list" : apply_list})


@login_required
@user_passes_test(is_jobless)
def cvcreate(request):
    employer = request.user
    employer_profile = employer.userprofile
    if request.method=="POST":
        form = CurriculumForm(request.POST)
        if form.is_valid():
            cv = form.save(commit=False)
            cv.profile = employer
            cv.cv_email = employer_profile.email
            cv.cv_fname = employer_profile.first_name
            cv.cv_lname = employer_profile.last_name
            cv.cv_dob = employer_profile.date_of_birth
            cv.save()
            return redirect ("board:seecv")
        else:
            message = "Please check your input for errors"
            form = CurriculumForm()
            return render(request, 'board/newcv.html', {"form" : form, "message" : message})
    else:
        form = CurriculumForm()
        return render(request, 'board/newcv.html', {"form" : form})

@login_required
@user_passes_test(is_jobless)
def cvview(request): #html exists
    try:
        employer = request.user
        seevee = Curriculum.objects.get(profile=employer)
    except Curriculum.DoesNotExist:
        raise Http404("You have not created a CV yet")
    return render(request, "board/seecv.html", {"seevee" : seevee})


@login_required
@user_passes_test(is_jobless)
def cvedit(request): #HTML exists
    employer = request.user
    employer_profile = employer.userprofile
    notseevee = employer.curriculum #Is it the one-to-one why I cannot access it by objects.get?
    #seevee = Curriculum.objects.get(profile=employer)   
    if request.method == "POST":
        form = CurriculumForm(request.POST)
        if form.is_valid():
            cve = form.save(commit=False)
            cve.profile = employer
            cve.cv_email = employer_profile.email
            cve.cv_fname = employer_profile.first_name
            cve.cv_lname = employer_profile.last_name
            cve.cv_dob = employer_profile.date_of_birth
            cve.save()
            return redirect("board:seecv")
        else:
            form = CurriculumForm(initial=model_to_dict(notseevee))

board/templates/board/base.html
<!DOCTYPE html>
<html lang="en-US">

<head>
  <meta charset="utf-8">
  <title>{% block title %}Job Board 1896{% endblock %}</title>
</head>
<body>
  <main>
    
    {% block content1 %}
    {% endblock %}

    {% block content3 %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block content2 %}
    {% endblock %}
  </main>
</body>
</html>

board/templates/board/change-password.html
{% extends "base.html" %}

{% block content1 %}
{% if user.is_authenticated %}
Hello,  {{user.username}}!
{%endif%}
{% endblock %}

{% block title %}Change Password{% endblock %}

{% block content %}
  <h2>Change Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ password_form.as_p }}
    <button type="submit">Change Password</button>
  </form>
{% endblock %}

board/templates/board/front.html
{% extends 'base.html' %}
{% load board_extras %}


{% block title %} Job Board 1896 - Front {% endblock %}

    
    {% block content1 %}
    {% if user.is_authenticated %}
        Hi  {{user.username}} !
        {% if request.user|has_group2:"Seeker" %}
        <p><a href="{% url 'board:seekerview' %}">Profile</a></p>
        {% elif request.user|has_group1:"Jobless" %}
        <p><a href="{% url 'board:userhome' %}">Profile</a></p>
        {% endif %}
        <p><a href="{% url 'board:logout' %}">Log Out!</a></p>

    {% else %}
        <p> You are not logged in!</p>
        <p> To interact with listings, please log in! </p>


        
    {% endif %}
    {% endblock %}

    {% block content %}
    {% if job_list %}
    <ul>
        {% for i in job_list %}
            <li> {{i.job_title}} at {{i.job_source}} posted on {{i.job_date}} 
                {%if request.user|has_group2:"Seeker" %} <a href="/board/seekeroneview/{{i.job_id}}"> See opening </a> {% else %} <a href="/board/front/{{i.job_id}}"> See opening </a> {% endif %} </li>
        {% endfor %}
    </ul>
    {% else %}
        <p> No job listings found.</p>
    {% endif %} 
    {% endblock %}

    {%block content2 %}
    {% if user.is_anonymous %}
    <p> <a href="{% url 'board:login' %}">
        <button>Log in!</button></a> 
    </p>
    
    <p>
    <a href="{% url 'board:register' %}">
        <button>Register!</button>
    </a>
    </p>
    {% endif %}
    {% endblock %}

board/templates/board/jobdelete.html
{% extends 'base.html' %}

{% block content1 %}
{% if user.is_authenticated %}
Hello,  {{user.username}}!
{%endif%}
{% endblock %}


{% if job_one %}
{%block title %} {{job_one.j_title}} {% endblock %}

{% block content %}


    <p><h2> Job Title: {{job_one.j_title}}</h2></p>
    <p><h3> Posted at: {{job_one.j_date}} </h3></p>
    <p><h3> Posted by: {{job_one.j_poster}}</h3></p>
    <p><h3> Contact info: {{job_one.email}}</h3></p> 

    <p><h2> Job category: </h2></p>
    <p><h4> {{job_one.j_category|linebreaks}} </h4></p>

    <p><h2> Job description: </h2></p>
    <p> {{job_one.j_description|linebreaks}} </p>
    
    <p><h2> Skill requirements: </h2></p>
    <p> {{job_one.j_reqs|linebreaks}} </p>

    <p><h2> About the Company: </h2></p>
    <p> {{user.userprofile.company_descript|linebreaks}} </p>

    
    <form action="/board/jobdelete/{{job_one.j_id}}" method="POST">
        {% csrf_token %}

    <p> Are you sure you want to delete this job posting? </p>
    <input type="submit" value="Yes, delete!"> 
    </form> 
    

    {%comment%}
    Add button and link to edit post instead.
    Add option to unpublish and turn into draft instead.
    
    {%endcomment%}


    <a href="/board/front/"> 
        <button>Back</button> 
    </a>

board/templates/board/jobedit.html
{% extends 'base.html' %}

{% block content1 %}
{% if user.is_authenticated %}
Hello,  {{user.username}}!
{%endif%}
{% endblock %}

{% block content %}

<h2> Edit Job Posting </h2>
<form method="POST" novalidate>
    {%csrf_token%}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>


{% endblock %}

board/templates/board/login.html
{% extends 'base.html' %}


{% block title %} Login {% endblock %}

{% block content %}
<h2> Log in</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Log In</button> 
</form>

<p><h2>{{message}}</h2></p>

<p>
<a href="{% url 'board:register' %}">
<button>Register!</button>
</a>
</p>
{% endblock %}

board/templates/board/openingsingle.html
{% extends 'base.html' %}
{% load board_extras %}

{% if job_one %}
    {% block title %} {{job_one.job_title}} {% endblock %}

    {% block content1 %}
    <p><h2> Job Title: {{job_one.job_title}}</h2></p>
    <p><h3> Posted at: {{job_one.job_date}} </h3></p>
    <p><h3> Posted by: {{job_one.job_source}}</h3></p>
    <p><h3> Contact info: {{job_one.email}}</h3></p> 

    <p><h2> Job category: </h2></p>
    <p><h4> {{job_one.job_field|linebreaks}} </h4></p>

    <p><h2> Job description: </h2></p>
    <p> {{job_one.job_desc|linebreaks}} </p>
    
    <p><h2> Skill requirements: </h2></p>
    <p> {{job_one.job_skills|linebreaks}} </p>

    <p><h2> About the Company: </h2></p>
    <p> {{job_one.job_about|linebreaks}} </p>
    {% endblock %}



    {% block content %}
        {% if user.is_authenticated  %}
            Hello,  {{user.username}}!
            <p><a href="{% url 'board:logout' %}">
            <button> Log out!</button> </a></p>
            {% if request.user|has_group1:"Jobless" %}
                <form action="/board/jobapply/{{job_one.job_id}}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Apply!"> 
                </form>

                <p><a href="{% url 'board:userhome' %}">
                <button> Home!</button> </a></p>                
            {% else %}
                User group check failed!
            {% endif %}

        {% else %}
            <p>You are not logged in! Login to continue</p>
            <p><a href="{% url 'board:login' %}">
            <button> Login!</button> </a></p>
        {% endif %}   
    {% endblock %}
   

{% else %}
    <p>Job posting may have been deleted or unpublished.</p>
{% endif %}
{% block content2 %} 
<p><a href="{% url 'board:front' %}">
<button>Back</button></a></p>
{% endblock %}

board/templates/board/registration.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" class="form-group">
	{% csrf_token %}
	<h2>Sign Up</h2>
	{{ user_form.as_p }}
	<input type="submit" value="Register" />
</form>


	
<p> IMPORTANT! You need to fill both forms to register a new user </p>

{% endblock content%}

board/templates/board/seeapply.html
{% extends 'base.html' %}
{% load board_extras %}

{%comment%}
This view shows a cv side by side with a motivation Letter

In the title or up high, it should show both cv date and apply date, one on either side, also job for which the application applies


{%endcomment%}

{% block content1 %}

{% if observer.is_authenticated %}
Hello,  {{observer.username}}!
{%endif%}

{% if seevee %}
    <p><h3>Last updated at: {{seevee.cv_date}}</h3></p> 

    <p><h2> I Basic information</h2></p>
    <p><h4> Given names: {{seevee.cv_fname}} </h4></p>
    <p><h4> Last name: {{seevee.cv_lname}} </h4></p>
    <p><h4> Date of birth: {{seevee.cv_dob}} </h4></p>
    <p><h4> Email: {{seevee.cv_email}} </h4></p>

    <p><h2> II Education</h2></p>
    <p> {{seevee.cv_education|linebreaks}} </p>

    <p><h2> III Job History</h2></p>
    <p> {{seevee.cv_career|linebreaks}} </p>

    <p><h2> IV Technical Skills</h2></p>
    <p> {{seevee.cv_skills|linebreaks}} </p>

    <p><h2> V About Me</h2></p>
    <p> {{seevee.cv_other|linebreaks}} </p>

{% endif %}
{% endblock %}

{% block content3 %}
{% if application %}
    <p><h3>Motivation letter</h3></p>
    <p> {{application.motivation|linebreaks}} </p>
{% endif %}
{% endblock %}

{% block content %}
{% endblock %}

{% block content2 %}
{% if request.user|has_group1:"Jobless" %}
<p><a href="{% url 'board:userhome' %}">
    <button> Home!</button> </a></p> 

<form action="/board/applycancel/{{application.apply_id}}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Rescind application"> 
</form>

{% elif request.user|has_group2:"Seeker" %}
<p><a href="{% url 'board:seekerview' %}">
    <button> Back</button> </a></p> 
{% else %}
Group check failed
{% endif %}

<p><a href="{% url 'board:exportcv' %}">
    <button> Export as PDF </button></a></p> 

<p><a href="{% url 'board:logout' %}">
    <button>Log Out!</button></a></p>

{% endblock %}

board/templates/board/seecv.html
{% extends 'base.html' %}

{% block content1 %}
{% if user.is_authenticated %}
Hello,  {{user.username}}!
{%endif%}
{% endblock %}

{%if seevee %}

    {% block title %} {{seevee.cv_fname}} {{seevee.cv_lname}}'s CV.  {% endblock %}

    {% block content %}
    <p><h2> I Basic information</h2></p>
    <p><h4> Given names: {{seevee.cv_fname}} </h4></p>
    <p><h4> Last name: {{seevee.cv_lname}} </h4></p>
    <p><h4> Date of birth: {{seevee.cv_dob}} </h4></p>
    <p><h4> Email: {{seevee.cv_email}} </h4></p>

    <p><h2> II Education</h2></p>
    <p> {{seevee.cv_education|linebreaks}} </p>

    <p><h2> III Job History</h2></p>
    <p> {{seevee.cv_career|linebreaks}} </p>

    <p><h2> IV Technical Skills</h2></p>
    <p> {{seevee.cv_skills|linebreaks}} </p>

    <p><h2> V About Me</h2></p>
    <p> {{seevee.cv_other|linebreaks}} </p>

    <p><h3>Last updated at: {{seevee.cv_date}}</h3></p> 


    
    <a href="{% url 'board:editcv' %}">
         <button>Edit CV</button>
    </a>
    
    <a href="{% url 'board:exportcv' %}">
        <button> Export as PDF </button>
    </a> 

    {% endblock %}

{% else %}

    <p> You have not created a CV yet.</p>

    <p><a href="{% url 'board:newcv' %}"> Would you like to create one?</a></p>

{% endif %}

{% block content2 %}
    <a href="{% url 'board:userhome' %}">
        <button>Back</button>
    </a>

{% endblock %}

board/templates/board/seekeredit.html
{% extends 'base.html' %}

{% block content1 %}


{% if user.is_authenticated %}
Hello,  {{user.username}}!
{%endif%}


{% if err %}
<p> Account edit form errors: {{ err }} </p>
{% endif %}


{% endblock %}


{% block content %}

<h2> Edit your company profile </h2>
<form method="POST" novalidate>
    {%csrf_token%}
    {{ account_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Save" />
</form>



<p>Want to change account password instead? Here's a button</p>
<p><a href="{% url 'board:password-change' %}">
    <button>Change Password</button></a></p>

<p><a href="{% url 'board:seekerview' %}">
    <button>Back</button>
</a></p>


{% endblock %}

board/templates/board/seekerview.html
{% extends 'base.html' %}



{% block title %} Job Board 1896: {{current_user.userprofile.company_name}}'s Desktop {% endblock %}

    {%block content1 %}
        <p><h2> Job Board 1896: {{current_user.userprofile.company_name}}'s Desktop </h2></p>

        <p>Your Job posting pulls data from your User Profile, so it would be wise to complete that</p>
        <p><a href="{% url 'board:seekeredit' %}">Edit Profile</a></p>
    
        <p><a href="{% url 'board:jobcreate' %}">Add Job Opening</a></p>

        <p><a href="{% url 'board:logout' %}">Log Out!</a></p>

        <p><a href="{% url 'board:front' %}">Front page</a></p>
    
    {% endblock %}

    
    {% block content %}
    {% if seeker_job_list %}
    
    here is a list of job openings you have posted:
    <ul>
        {% for i in seeker_job_list %}
            <li><p> {{i.job_title}} posted on {{i.job_date}} 
            <a href="/board/seekeroneview/{{i.job_id}}"> See opening </a>  
            This post is {%if i.published == True %}  published {% else %} unpublished {% endif %} </p> 
            {%comment%}
            {% if applications %}
            The following users have applied to this opening:
            <ul>
                {% for k in applications %}
                <li><p> {% if k.is_active == True and k.sourcejob == i.job_id %} User {{k.applicant}} on {{k.applydate}} applied - 
                <a href="/board/seeapply/{{k.apply_id}}"> See application</a> {% else %} This application has been rescinded. {% endif %}</p></li>  
                {% endfor %}
            </ul>
            {% endif %}
            {%endcomment%}
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p> You have not posted any job openings yet.</p>
    {% endif %} 
    {% endblock %}

board/templates/board/userview.html
{% extends 'base.html' %}



{% block title %} Job Board 1896: {{jobless.username}}'s Desktop {% endblock %}

    
    {% block content1 %}
    <p><h2> Job Board 1896: {{jobless.username}}'s Desktop </h2></p>

    <p>Your CV pulls data from your User Profile, so it would be wise to complete that</p>
    <p><a href="{% url 'board:useredit' %}">Edit Profile</a></p>
    
    {%if seevee %}
    <p><a href="/board/cvview">See CV</a></p>
    <p><a href="/board/cvedit">Edit CV</a></p>
    {% comment %}<p><a href="{% url 'board:exportcv' %}">Export CV as PDF</a></p>{% endcomment %}
    {% else %}
    <p><h3>{{message}}</h3></p>
    <p><a href="{% url 'board:newcv' %}">New CV</a></p>
    {% endif %}
    {% endblock %}

    {% block content3 %}
    {% if apply_list %}
    
        You have applied for the following Job postings:
        <ul>
            {% for i in apply_list %}
            <li> {%if i.is_active == True %} {{i.sourcejob.job_title}} at {{i.sourcejob.job_user.company_descript}}
                 <a href="/board/seeapply/{{i.apply_id}}"> See application</a> {% else %}
                 You have rescinded your application {% endif %} </li>
            {%endfor%}
        </ul>
    {%endif%}
    {% endblock %}




    {% block content2 %}
    <p><a href="{% url 'board:front' %}">See posted jobs</a></p>
    
    <p><a href="{% url 'board:logout' %}">Log Out!</a></p>
    {% endblock %}


    